# This is a basic workflow to help you get started with Actions

name: Annually reset academic repo

# Controls when the action will run.
on:
  # Triggers the workflow on every 1st of January
  schedule:
    - cron: "0 0 1 1/12 *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "close-prs"
  close-prs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: List pull requests and close all of them
        run: |
          echo "Create a list with each currently active pull request id"
          prs=$(gh pr list | cut -f 1)
          echo "Close all of them"
          for pr in $prs
          do
            gh pr close $pr
          done
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: echo "All currently active pull requests were closed"
